set(UF2_STAGING_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/uf2-copyfiles.sh)
set(PIMORONI_UF2_MANIFEST ${CMAKE_CURRENT_LIST_DIR}/uf2-manifest.txt)
set(PIMORONI_ROMFS_DIR ${CMAKE_CURRENT_LIST_DIR}/romfs)
include(${CMAKE_CURRENT_LIST_DIR}/../common.cmake)
